<h1><?= $heading ?></h1>
<?php if ($error): ?>
	<div class="p-3 mb-2 bg-danger text-white"><?= $error ?></div>
<?php endif ?>
<form method="post" action="AddPerson">
	<div class="form-group row">
		<label for="name" class="col-sm-2 col-form-label">Name</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" name="name" id="name" value="<?= $name ?>">
		</div>
	</div>
	<div class="form-group row">
		<label for="email" class="col-sm-2 col-form-label">E-Mail</label>
		<div class="col-sm-10">
			<input type="email" class="form-control" name="email" id="email" value="<?= $email ?>"/>
		</div>
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>
</form>
